export const PICTURE_CARD_PROMPTS: string[] = [
  "A winding path disappearing into a misty forest.",
  "A single, ornate key floating in a vast, empty room.",
  "A clock melting over a tree branch in a surreal landscape.",
  "Two hands made of smoke reaching for each other but not touching.",
  "A lone figure on a stone bridge looking at their distorted reflection in the water.",
  "A house being carried away by a flock of birds.",
  "A child planting a glowing seed in barren soil.",
  "A massive, ancient book opened to a blank page.",
  "A person weaving a tapestry from threads of light.",
  "A door standing alone in the middle of a desert.",
  "A boat made of paper navigating a stormy sea in a teacup.",
  "A face with a crack in it, from which flowers are growing.",
  "A ladder leaning against a cloud.",
  "A carousel with mythical creatures instead of horses.",
  "A tree with roots exposed, reaching for the sky instead of the ground.",
  "A silhouette holding an umbrella as stars rain down instead of water.",
  "A chess board with pieces that are alive and moving on their own.",
  "An empty swing set on a vibrant, colorful hill.",
  "A bird in a cage, but the cage door is wide open.",
  "A person holding a mask that looks exactly like their own face.",
  "A lighthouse casting a beam of darkness instead of light.",
  "A shattered mirror with each piece reflecting a different reality.",
  "A figure juggling planets in the cosmos.",
  "A road that splits into countless different paths.",
  "A single candle flame burning underwater.",
  "A puppet cutting its own strings.",
  "A message in a bottle washed up on a shore made of gears and cogs.",
  "A person building a wall with one hand and dismantling it with the other.",
  "An anchor made of clouds floating in the sky.",
  "A garden where musical instruments grow from the ground.",
  "A heart locked inside a block of ice.",
  "A person looking through a telescope at their own past.",
  "A maze with no entrance or exit.",
  "A set of footprints leading into a solid wall.",
  "A figure made of constellations sitting on the moon.",
  "A waterfall flowing upwards.",
  "A lone wolf howling at a shattered moon.",
  "A person fishing in a puddle and pulling out a star.",
  "A giant ear listening to the whispers of the earth.",
  "A tree that sheds leaves of paper with words on them.",
  "A ship sailing on a sea of sand.",
  "A person with a head full of swirling galaxies.",
  "A bridge made of woven rainbows connecting two cliffs.",
  "A single feather falling onto a still, dark lake.",
  "A window looking out onto a scene from a dream.",
  "A figure trying to catch lightning in a jar.",
  "A phonograph playing the sound of silence.",
  "A group of people huddled around a fire that gives no warmth.",
  "A keyhole with an eye looking back from the other side.",
  "A compass with needles pointing in all directions.",
  "A tree growing inside a transparent human silhouette.",
  "A person shedding their skin like a snake.",
  "A city skyline at the bottom of the ocean.",
  "A musician playing a piano with keys made of ice.",
  "A child conducting an orchestra of woodland creatures.",
  "A figure painting a sunset that is happening in real-time.",
  "A tightrope walker balancing between two skyscrapers in a storm.",
  "A room where gravity is pulling everything towards the walls.",
  "A person holding a dandelion, with seeds of ideas blowing away.",
  "A giant hourglass where the sand is flowing upwards.",
  "A book whose words rearrange themselves each time it's read.",
  "A person following a map that is blank.",
  "A shadow that is more colorful and vibrant than the person casting it.",
  "A flower blooming in a desert of cracked earth.",
  "A person whispering a secret to a statue.",
  "A nest with a single, glowing egg inside.",
  "A figure wearing a cloak made of the night sky.",
  "A spiderweb covered in morning dew, reflecting the world.",
  "A person trying to piece together a broken plate.",
  "A storm in a snow globe.",
  "A set of Russian dolls, each one holding a different emotion.",
  "A figure with wings made of paper.",
  "A giant magnifying glass focused on a single blade of grass.",
  "A person sitting on a pier, with their feet in a sea of clouds.",
  "A hot air balloon in the shape of a human heart.",
  "A child talking to their reflection in a puddle.",
  "A tree with human hands as branches.",
  "A river flowing with liquid light.",
  "A person watering a plant that is growing through a concrete floor.",
  "A mask that is crying.",
  "A figure trapped inside a soap bubble.",
  "A bird flying through a sky filled with floating islands.",
  "A person building a sandcastle against an incoming tide.",
  "A door that opens into a starry cosmos.",
  "A figure holding a sphere that contains a perfect, tiny world.",
  "A labyrinth made of mirrors.",
  "Two figures back to back, growing from the same tree trunk.",
  "A single, perfect raindrop about to hit a still surface."
];

export const WORD_CARDS: string[] = [
  "自由", "恐懼", "等待", "改變", "愛", "失落", "希望", "憤怒",
  "喜悅", "悲傷", "力量", "軟弱", "連結", "孤獨", "旅程", "家",
  "工作", "玩樂", "給予", "接受", "開始", "結束", "信任", "背叛",
  "罪惡感", "純真", "權力", "無助", "成長", "停滯", "友誼", "衝突",
  "豐盛", "匱乏", "真相", "欺騙", "勇氣", "猶豫", "療癒", "創傷",
  "父親", "母親", "孩子", "自我", "身體", "心智", "心靈", "自然",
  "放手", "緊抓", "幻象", "清晰", "混亂", "秩序", "溝通", "沉默",
  "慾望", "冷漠", "目的", "空虛", "慈悲", "評判", "感謝", "怨恨",
  "原諒", "責備", "耐心", "急躁", "信念", "懷疑", "成功", "失敗",
  "創造力", "無聊", "好奇", "不在乎", "親密", "距離", "責任", "逃避",
  "接納", "抗拒", "智慧", "無知", "慷慨", "自私", "慶祝", "哀悼",
  "臣服", "控制", "自發", "常規", "真實", "偽裝", "脆弱", "保護"
];

export const HIGHER_SELF_QUOTES: string[] = [
    "我允許自己停下腳步，感受此刻呼吸，並接受自己已經做得足夠。",
    "今天的我不需要完美，能真誠活著，已經是一份值得讚許的禮物。",
    "當我安靜下來，我能聽見內心深處溫柔的聲音，指引我前行。",
    "我的直覺是珍貴的指引，它提醒我在選擇中保持真實與清醒。",
    "我給自己一個擁抱，讓身體記得安全、溫暖與無條件的愛。",
    "我能與過去和解，不再被舊有傷痛束縛，給自己嶄新的空間。",
    "耐心是送給自己的禮物，我允許一切慢慢發生，無需急著追趕。",
    "幸福不是遠方的目標，而是我願意在當下看見並擁抱的小片刻。",
    "我正一點一滴成為完整的自己，每個不完美都值得被理解。",
    "我允許自己真實表達需求，不再隱藏渴望，而是勇敢地說出來。",
    "我的價值不依賴他人評價，我存在本身就是不可取代的力量。",
    "我願意學習原諒，不是為了別人，而是讓自己能更自在地呼吸。",
    "我有權利對不合適的事說「不」，並保護自己的界線與能量。",
    "我尊重自己的節奏，無需比較，也不必迎合任何人的期待。",
    "學會愛自己是漫長旅程，但每一天我都在走向更深的自我接納。",
    "我的情緒像海浪，來了又去，帶給我理解自己需求的深刻訊號。",
    "我允許自己感受悲傷，眼淚是心靈的出口，而不是軟弱的標記。",
    "憤怒提醒我內心有在乎的事，我選擇用溫柔方式表達與保護。",
    "當我擁抱喜悅，它會擴散到生活的每個角落，照亮我和他人。",
    "哀傷是一種轉化的力量，它讓我更懂得珍惜所擁有的當下。",
    "當眼淚落下時，我能安靜陪伴自己，不急著推開這份真實情感。",
    "我正在學習安撫自己，像母親對孩子般溫柔，接住每份不安。",
    "不安提醒我需要安全感，我選擇透過行動與信任來建立基礎。",
    "恐懼出現時，我依然擁有勇氣，它不會奪走我前進的可能。",
    "平靜不是外在給予的，而是我能隨時回到內心找到的歸宿。",
    "我的笑容是力量，它能療癒自己，也能傳遞溫暖給世界。",
    "情緒不會永遠停留，它們如風，來過之後，也會慢慢散去。",
    "我尊重內心的起伏，因為這代表我依然真實地活著並感受著。",
    "我的感受是獨一無二的，它們值得被傾聽與善待，而非忽視。",
    "每份情緒背後都有禮物，帶來成長、提醒與更多生命的深度。",
    "我願意真誠與人連結，同時也允許自己保持適當的距離與空間。",
    "我值得被溫柔對待，因為我的存在本身就有無可取代的價值。",
    "我能用清晰而溫柔的方式，讓他人聽見我真實的想法與需要。",
    "在關係裡，我和對方同樣重要，彼此的需求都值得被看見。",
    "我允許自己需要別人，這並不代表軟弱，而是人性的真實。",
    "我不必討好所有人，真誠的我才會吸引真正契合的關係。",
    "說出「不」是我的權利，這樣我才能守護自己真正的界線。",
    "愛與自由能夠共存，健康的關係不會限制我的成長與選擇。",
    "我的存在本身足以被愛，我不需要透過表現來證明價值。",
    "我能自由給予愛，也能安心接收愛，讓能量雙向流動。",
    "我尊重自己的界線，也同樣尊重他人的界線與選擇。",
    "我能在關係中保持自己，不必失去真實來換取認同。",
    "不合適的人離開，是讓我更接近真正懂得珍惜我的人。",
    "我值得擁有安全、信任又充滿溫度的親密關係。",
    "關係是互相滋養的旅程，我願意用愛與誠意來守護它。",
    "我的身體是最忠實的伙伴，它從未停止支持我的每一步。",
    "我感謝身體陪我走到今天，即使不完美也值得被擁抱。",
    "疲憊提醒我需要休息，這不是懶惰，而是對自己負責。",
    "我願意好好餵養自己，讓身體獲得需要的能量與滋養。",
    "每一次呼吸都是禮物，它帶來平靜，也帶來新的力量。",
    "痛苦是身體的訊號，它提醒我去傾聽並給予關愛。",
    "我願意細心傾聽身體的聲音，而不是忽視它的需求。",
    "我的身體不必符合標準，它的獨特就是一種美麗。",
    "我願意尊重身體的極限，不再強迫自己過度消耗。",
    "健康是一份寶藏，我能透過日常選擇來守護它。",
    "我能與身體建立友好關係，像朋友般彼此支持。",
    "身體有它的節奏，我願意耐心等待並善待它。",
    "我允許自己慢慢修復，療癒不需要急著完成。",
    "我的身體擁有自我療癒的能力，我選擇相信它。",
    "我感謝自己還能感受世界，這是生命的奇蹟。",
    "金錢只是能量的交換，它不決定我的價值與幸福感。",
    "我值得擁有豐盛，因為我的付出與努力都值得回報。",
    "我的努力不會白費，它們最終會帶來被看見的成果。",
    "我能自由選擇金錢的流向，讓它服務於我的生活。",
    "不比較也能安心生活，幸福來自心境而非擁有多少。",
    "我與金錢的關係正在改善，它成為支持而非壓力。",
    "我允許自己接受財富，因為這代表我能更好地分享。",
    "真正的安全感來自內在，它不僅僅依靠金錢累積。",
    "我正在養成健康的習慣，讓生活逐漸走向平衡穩定。",
    "我能在努力之間找到休息，讓工作與生活更加和諧。",
    "我允許自己享受生活中的小確幸，無需感到愧疚。",
    "簡單也是一種美好，過多的追逐只會模糊心的方向。",
    "我值得擁有舒適的空間，讓自己可以安心休憩。",
    "未來是可以規劃的，而我一步步正走在實現的路上。",
    "我相信資源會流向我，因為我正敞開去迎接它們。",
    "我有能力創造新的開始，每一步都會為未來打下基礎。",
    "未來不需急著知道答案，旅程本身也蘊含珍貴的意義。",
    "每一步努力都在累積力量，為我鋪設出更堅實的道路。",
    "我相信自己會找到方向，即使現在仍在摸索與等待。",
    "我是自己最穩定的支持者，無論何時都能依靠自己。"
];